name: .NET

on:
  push:
    branches: [ "main", "Food-Recall-Notif-App" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install .NET Workloads
        run: dotnet workload restore
      - name: Restore nuget packages
        run: nuget restore Food-Recall-Notif/Food-Recall-Notif.sln
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
